name: smartvestment

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.6+6

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  speech_to_text: ^7.0.0
  video_player: ^2.5.0
  logger: ^2.5.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.11.0
  google_sign_in: ^6.2.2
  firebase_database: ^11.2.0
  local_auth: ^2.1.6
  cloud_firestore: ^5.6.3
  intl: ^0.19.0
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.0
  provider: ^6.0.3
  flutter_tts: ^4.2.2
  permission_handler: ^11.0.1
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  flutter_background_service: ^5.0.1
  dart_openai: ^4.0.0
  shared_preferences: ^2.5.2
  firebase_remote_config: ^5.4.0
  firebase_analytics: ^11.4.2
  file_picker: ^9.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff" # لون خلفية الأيقونة المتكيفة
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png" # للأندرويد فقط


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - lib/l10n/app_en.json
    - lib/l10n/app_ar.json 
    - assets/images/app_icon.png
    - assets/images/
    - assets/videos/
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/industrial_1/
    - assets/images/industrial_2/
    - assets/images/industrial_3/
    - assets/images/industrial_4/
    - assets/images/industrial_5/
    - assets/images/industrial_6/
    - assets/images/realestate_1/
    - assets/images/realestate_2/
    - assets/images/realestate_3/
    - assets/images/realestate_4/
    - assets/images/realestate_5/
    - assets/images/realestate_6/